---
title: "Hypothesis 1"
author: "Katie Warburton"
format: html
editor: visual
execute:
    code-fold: true
    code-summary: "Show the code"
---

### Imports

```{r message=FALSE, warning=FALSE, results='hide'}
library(stringr) 
library(tidyverse) 
library(dplyr) 
library(ggplot2) 
library(lmtest) 
library(parameters) 
library(mclogit) 
library("rcompanion")


set.seed(13)
```

### Data

```{r}
df <- read.csv('../Results/level2_trial_data.csv',  na.strings=c("","NA"))  
items <- sprintf("I%02d", 9:23)
```

## Hypothesis 1a

Order affects the assignment of items to categories A, B, X

```{r}
df_1a <- df[df$ORDER != 'a',]
long_1a <- df_1a %>% pivot_longer(cols=all_of(items), 
                                  values_to = 'CAT') %>% 
  drop_na() %>% 
  select(all_of(c('P_ID', 'DEPTH', 'LOC', 'ORDER', 'CAT', 'STIMULI', 'POOL')))

long_1a$CAT <- relevel(as.factor(long_1a$CAT), ref='X')
long_1a$ORDER <- relevel(as.factor(long_1a$ORDER), ref='m')


                

```

### Left

```{r}
df_L <- long_1a[long_1a$LOC == 'L',]

lm_1 <- mblogit(
   formula = CAT ~ 1 + ORDER,
   random = list(~1|STIMULI, ~1|P_ID),
    control = mmclogit.control(inner.optimizer = 'CG' ),
   data = df_L)

lm_0 <- mblogit(
   formula = CAT ~ 1,
   random = list( ~1|STIMULI, ~1|P_ID),
    control = mmclogit.control(inner.optimizer = 'CG' ),
   data = df_L)

l_anova <- anova(lm_0, lm_1, test='Chisq')
l_anova
```

```{r}
coefs <- round(coef(lm_1), 2)
ci <- round(confint(lm_1), 2)

sprintf('%s & [%s, %s]', coefs[["L~(Intercept)"]], ci[1,1], ci[1, 2])

sprintf('%s & [%s, %s]', coefs[["L~ORDERf"]], ci[5,1], ci[5, 2])
sprintf('%s & [%s, %s]', coefs[["L~ORDERb"]], ci[3,1], ci[3, 2])


sprintf('%s & [%s, %s]', coefs[["R~(Intercept)"]], ci[2,1], ci[2, 2])

sprintf('%s & [%s, %s]', coefs[["R~ORDERf"]], ci[6,1], ci[6, 2])
sprintf('%s & [%s, %s]', coefs[["R~ORDERb"]], ci[4,1], ci[4, 2])
```

### Centered

```{r}
df_C <- long_1a[long_1a$LOC == 'C',]

cm_1 <- mblogit(
   formula = CAT ~ 1 + ORDER,
   random = list(~1|STIMULI, ~1|P_ID),
   control = mmclogit.control(inner.optimizer = 'CG' ),
   data = df_C)

cm_0 <- mblogit(
   formula = CAT ~ 1,
   random = list(~1|STIMULI, ~1|P_ID),
   control = mmclogit.control(inner.optimizer = 'CG' ),
   data = df_C)

c_anova <- anova(cm_0, cm_1, test='Chisq')
c_anova
```

```{r}
coef <- round(coef(cm_1), 2)
ci <- round(confint(cm_1), 2)

sprintf('%s & [%s, %s]', coef[["L~(Intercept)"]], ci[1,1], ci[1, 2])

sprintf('%s & [%s, %s]', coef[["L~ORDERf"]], ci[5,1], ci[5, 2])
sprintf('%s & [%s, %s]', coef[["L~ORDERb"]], ci[3,1], ci[3, 2])


sprintf('%s & [%s, %s]', coef[["R~(Intercept)"]], ci[2,1], ci[2, 2])

sprintf('%s & [%s, %s]', coef[["R~ORDERf"]], ci[6,1], ci[6, 2])
sprintf('%s & [%s, %s]', coef[["R~ORDERb"]], ci[4,1], ci[4, 2])
```

### Right

```{r}
df_R <- long_1a[long_1a$LOC == 'R',]

rm_1 <- mblogit(
   formula = CAT ~ 1 + ORDER,
   random = list(~1|STIMULI, ~1|P_ID),
   control = mmclogit.control(inner.optimizer = "CG"),
   data = df_R)

rm_0 <- mblogit(
   formula = CAT ~ 1,
   random = list(~1|STIMULI, ~1|P_ID),
    control = mmclogit.control(inner.optimizer = "CG"),
   data = df_R)

r_anova <- anova(rm_0, rm_1, test = "Chisq")
r_anova
```

```{r}
coef <- round(coef(rm_1), 2)
ci <- round(confint(rm_1), 2)

sprintf('%s & [%s, %s]', coef[["L~(Intercept)"]], ci[1,1], ci[1, 2])

sprintf('%s & [%s, %s]', coef[["L~ORDERf"]], ci[5,1], ci[5, 2])
sprintf('%s & [%s, %s]', coef[["L~ORDERb"]], ci[3,1], ci[3, 2])


sprintf('%s & [%s, %s]', coef[["R~(Intercept)"]], ci[2,1], ci[2, 2])

sprintf('%s & [%s, %s]', coef[["R~ORDERf"]], ci[6,1], ci[6, 2])
sprintf('%s & [%s, %s]', coef[["R~ORDERb"]], ci[4,1], ci[4, 2])
```

### Overall

```{r}
m_1 <- mblogit(
   formula = CAT ~ 1 + ORDER,
   random = list(~1|STIMULI, ~1|P_ID, ~1|LOC), 
   control = mmclogit.control(inner.optimizer = "CG"),
   data = long_1a)

m_0 <- mblogit(
   formula = CAT ~ 1,
   random = list(~1|STIMULI, ~1|P_ID, ~1|LOC), 
   control = mmclogit.control(inner.optimizer = "CG"),
   data = long_1a)

o_anova <- anova(m_0, m_1, test = "Chisq")
o_anova
```

```{r}
coef <- round(coef(m_1), 2)
ci <- round(confint(m_1), 2)

print('L vs. X')
sprintf('Intercept: %s & [%s, %s]', coef[["L~(Intercept)"]], ci[1,1], ci[1, 2])
sprintf('Forward: %s & [%s, %s]', coef[["L~ORDERf"]], ci[5,1], ci[5, 2])
sprintf('Backward: %s & [%s, %s]', coef[["L~ORDERb"]], ci[3,1], ci[3, 2])


print('R vs. X')
sprintf('Intercept: %s & [%s, %s]', coef[["R~(Intercept)"]], ci[2,1], ci[2, 2])

sprintf('Forward: %s & [%s, %s]', coef[["R~ORDERf"]], ci[6,1], ci[6, 2])
sprintf('Backward: %s & [%s, %s]', coef[["R~ORDERb"]], ci[4,1], ci[4, 2])
```

Using chi-squared for order

```{r}
left_cat_by_order <- table(df_L$ORDER, df_L$CAT)

left_cat_by_order

round(t(apply(left_cat_by_order,1, function(x) x/sum(x))), 3)

t_pool <- chisq.test(left_cat_by_order)
t_pool 
round(cramerV(left_cat_by_order), 2)

chisq.test(left_cat_by_order)$stdre
```

```{r}
center_cat_by_order <- table(df_C$ORDER, df_C$CAT)

center_cat_by_order

round(t(apply(center_cat_by_order,1, function(x) x/sum(x))), 3)

t_pool <- chisq.test(center_cat_by_order)
t_pool 
round(cramerV(center_cat_by_order), 2)

chisq.test(center_cat_by_order)$stdre
```

```{r}
right_cat_by_order <- table(df_R$ORDER, df_R$CAT)

right_cat_by_order

round(t(apply(right_cat_by_order,1, function(x) x/sum(x))), 3)

t_pool <- chisq.test(right_cat_by_order)
t_pool 
round(cramerV(right_cat_by_order), 2)

chisq.test(right_cat_by_order)$stdre
```

```{r}
cat_by_order <- table(long_1a$ORDER, long_1a$CAT)

cat_by_order

round(t(apply(cat_by_order,1, function(x) x/sum(x))), 3)

t_pool <- chisq.test(cat_by_order)
t_pool 
round(cramerV(cat_by_order), 2)

chisq.test(cat_by_order)$stdre
```
